### ISSUE TITLE
Native Groovy Console App

### ISSUE THREAD

**Issue by ibinti** [bugvm/bugvm-helloworld#1]
Need to figure out which Groovy library classes require forcelinkclasses.

**Comment by ibinti** [comment]
Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngine
        at java.lang.VMClassLoader.findClassInClasspathForLoader(Native Method)
        at java.lang.PathClassLoader.findClass(PathClassLoader.java)
        at java.lang.ClassLoader.loadClass(ClassLoader.java)
        at java.lang.ClassLoader.loadClass(ClassLoader.java)
        at java.lang.reflect.Method.getParameterTypes(Native Method)
        at java.lang.reflect.Method.getParameterTypes(Method.java)
        at java.lang.reflect.Method.getParameterTypes(Method.java)
        at org.codehaus.groovy.reflection.CachedMethod.getPT(CachedMethod.java)
        at org.codehaus.groovy.reflection.ParameterTypes.getParametersTypes0(ParameterTypes.java)
        at org.codehaus.groovy.reflection.ParameterTypes.getParameterTypes(ParameterTypes.java)
        at org.codehaus.groovy.reflection.CachedMethod.compareToCachedMethod(CachedMethod.java)
        at org.codehaus.groovy.reflection.CachedMethod.compareTo(CachedMethod.java)
        at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java)
        at java.util.Arrays.sort(Arrays.java)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java)
        at org.codehaus.groovy.reflection.CachedClass.getMethods(CachedClass.java)
        at org.codehaus.groovy.runtime.m12n.SimpleExtensionModule.createMetaMethods(SimpleExtensionModule.java)
        at org.codehaus.groovy.runtime.m12n.SimpleExtensionModule.getMetaMethods(SimpleExtensionModule.java)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java)

**Comment by ibinti** [comment]
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java)

**Comment by ibinti** [comment]
Hmm. Some of classes Groovy requires seem not implemented in the BugVM class library.
I will try adding missing classes.
